### ISSUE TITLE
데브 이벤트 상단 공지 배너(?) 변환

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Android#11]
@jisungbin 님 안녕하세요~

좀 되었지만 OPGG 경진대회는 잘 마치셨을까요~^^

![image](https://user-images.githubusercontent.com/28642484/141129104-6305f29d-e34a-4741-bebd-f45f9058cc9d.png)

다름이 아니라 데브 이벤트 공지 배너를 변경하였습니다.

지난번 크롤링 코드 리뷰할때 공지 배너쪽 상단은 보지 않았던걸로 기억하는데 문제가 없는지 혹시 확인차 이슈 남깁니다

감사합니다^^

**Comment by jisungbin** [comment]
확인했습니다! 문제 없는거 같고, 감사합니다 :)

**Comment by KoEonYack** [comment]
@jisungbin 님, 빠른 검토 감사합니다~ 
좋은 밤 되세요~~! 👍
