### ISSUE TITLE
Renovate App 설치 문의

### ISSUE THREAD

**Issue by jisungbin** [brave-people/Dev-Event-Android#14]
안녕하세요. 의존성 버전 자동 관리를 위해 Renovate 를 사용하고자 합니다.
조직 혹은 이 저장소에 Renovate GitHub Application 을 설치해 주실 수 있나요?

https://github.com/marketplace/renovate

**Comment by jisungbin** [comment]
@KoEonYack

**Comment by KoEonYack** [comment]
@jisungbin 님~

<img width="298" alt="image" src="https://user-images.githubusercontent.com/28642484/213193271-09343241-3988-4eaa-9418-c5f2d41a8427.png">

설치했습니다! 확인해보세요 :)

**Comment by jisungbin** [comment]
> @jisungbin 님~ 설치했습니다! 확인해보세요 :)

작동 확인했습니다! 감사합니다.
