### ISSUE TITLE
앱 출시를 축하해요~!!

### ISSUE THREAD

**Issue by KoEonYack** [brave-people/Dev-Event-Android#6]
@jisungbin 님, 안녕하세요!

안드로이드 앱 출시를 축하해요~!

dev event에 홍보용 이미지를 제작해보고 dev event에 반영했어요

마음에 들었으면 좋겠습니다

![image](https://user-images.githubusercontent.com/28642484/123543136-1c954200-d788-11eb-8eb0-3d04ee865c6a.png)

다만,, 제가 안드로이드 폰이 없어서 돌려보지는 못했네요,,!

**Comment by jisungbin** [comment]
@KoEonYack 님, 제가 디자인은 잘 못해서 따로 만들지 못하였는데 대신 만들어주셨다니 저야 엄청 감사하게 느끼고 있습니다!
만들어주신 이미지 만족스럽고 감사합니다 :)

다만, 제가 스크린샷을 찍을 때 문제가 해결되지 않은 앱으로 찍었는지 이벤트가 중복되게 찍혔더라구요
그래서 새로 [스크린샷](https://github.com/brave-people/Dev-Event-Android/blob/master/images/main.png)을 업로드 하였는데, 새로운 스크린샷으로 앱 이미지 변경이 가능할까요?

제가 따로 다시 만들어보려고 했는데 위에 만들어주신 이미지랑 느낌이 너무 달라서 이상하더라구요 ㅠ

**Comment by jisungbin** [comment]
추가로 iOS 작업은 7월  중순쯤에 iMac이 오는 대로 바로 작업 들어갈 예정입니다!
6월 초에 시켰는데 배달이 한 달 넘게 걸린다고 하네요 ㅠ

**Comment by KoEonYack** [comment]
@jisungbin 네~ 제가 수정해둘께요~!

이번에 나온 M1 맥을 주문하셨나요~! 오래 기다려야하군요~!

Google Meete으로 간단하게 어떻게 구현했는지, 어떤 주기로 데이터를 크롤링하는지, 발전 방향 등등 이야기를 듣고 사담을 나누는 시간을 갖고 싶은데요~~!! 

부담스러울것 없이 그냥 친구에게 개발한 이야기 썰푼다는 생각이면 될것같아요~

혹시 괜찮으실까요?!

**Comment by jisungbin** [comment]
@KoEonYack M1 iMac 주문했습니다!

Google Meet 가능합니다, 전 시간은 다 괜찮은데 언제 진행하실까요?

**Comment by KoEonYack** [comment]
@jisungbin 

이번주 수요일 저녁 9시 괜찮을까요~?!

**Comment by jisungbin** [comment]
@KoEonYack 넵, 그럼 그때 봬요.

**Comment by KoEonYack** [comment]
@jisungbin 

21300035@handong.edu으로 번호를 보내주실 수 있으실까요~~!?

번호를 알면 참석 링크를 바로 보내드릴 수 있겠어요~!!!

**Comment by jisungbin** [comment]
@KoEonYack  번호가 핸드폰 번호 말씀하시는 건가용? 일단 구글미트 회의 코드는 mys-ryhx-qww 입니당

**Comment by KoEonYack** [comment]
@jisungbin 

아~ 핸드폰 번호입니다~!

**Comment by jisungbin** [comment]
@KoEonYack 아하 알겠습니다! (보냈습니다)

**Comment by KoEonYack** [comment]
@jisungbin 잘 지내셨나요?!

메일을 못받았는데,,^^;; 번거롭지 않으시다면 covenant.ko@kakao.com 로 다시 보내주실 수 있으실까요?!

내일 밤9시 저와 제가 속한 회사의 입사 동기이자 안드로이드 개발자 참석할 예정입니다~

그 분이 앱 설치해서 사용해보셨고 작성하신 코드도 보셨습니다. (잘하신다고 칭찬을 하시네요 ㅎㅎ)

실력도 좋으시고 인사이트도 뛰어난 분이시니

혹시 구현상에서 궁금했던거나 기타 커리어든 무엇이든 궁금한게 있다면 이번 만남을 잘 활용해보는것도 좋겠습니다~!

**Comment by jisungbin** [comment]
@KoEonYack 앗, 메일이 안갔나요?
![image](https://user-images.githubusercontent.com/40740128/123823203-f0b8be80-d937-11eb-9669-35896dfeab80.png)

일단 좋은 기회 주셔서 감사하고 다시 주신 이메일로 메일 재전송 하겠습니다! 감사합니다 :)
