### ISSUE TITLE
앱 뒤로가기

### ISSUE THREAD

**Issue by jiimy** [brave-people/Dev-Event-Android#9]
앱에서 메인화면에서 뒤로가기시 
한번 더 물어봤으면 좋겠습니다. 
1. 뒤로가기를 잘못 눌렀을시에도 방지할수있고, 
2. 목록을 선택하여 정보를 보고 있는중에도뒤로가기 누를시 앱이 닫혀버립니다.

**Comment by jisungbin** [comment]
제보 감사합니다!
다음 업데이트에서 수정하겠습니다.

**Comment by jisungbin** [comment]
처리 완료 했습니다!
버그 수정 및 기능 추가 까지 마치고, 다음 업데이트에 적용될 예정입니다.

다시 한 번 제보 감사합니다 :)
